server {
  listen 80;
  server_name _;

  root /usr/share/nginx/html;
  index index.html;

  location /images/ {
    alias /usr/share/nginx/html/images/;
    expires 7d;
    add_header Cache-Control "public, immutable";
  }

  location / {
    try_files $uri $uri/ /index.html;
  }
}
